version: '3.8'
services:
  postgres-auth:
    image: postgres:15
    container_name: dating-app-postgres-auth
    environment:
      POSTGRES_DB: dating_auth
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"  # Using 5433 to avoid conflicts
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U auth_user -d dating_auth"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-auth:
    image: redis:7-alpine
    container_name: dating-app-redis-auth
    ports:
      - "6380:6379"  # Using 6380 to avoid conflicts
    volumes:
      - redis_auth_data:/data

volumes:
  postgres_auth_data:
  redis_auth_data: